---
# tasks file for bootstrap-rpi.yml
- block:
    - name: Check if connection against host is possible
      command: >
        ssh -o StrictHostKeyChecking=no -o User={{ ansible_user }} 
        -o ConnectTimeout=5 -o PreferredAuthentications=publickey 
        -o PubkeyAuthentication=yes -i {{ ansible_ssh_private_key_file}}
        -p {{ ansible_port }} {{ ansible_host }}
      connection: local
      ignore_errors: false
      changed_when: False

    - include: bootstrap-rpi.yml
      vars:
        ansible_become: yes
      when: force_bootstrap |bool
  rescue:
    - name: Ask the user whether they want to force a bootstrap as it seems the SSH fingerprint has changed since previous execution
      pause:
        prompt: "This might look odd - Are you setting up a new device? - Security advise: cancel this operation if not. Otherwise, press any key"

    - name: Remove SSH Fingerprint from known_hosts
      ignore_errors: true
      delegate_to: localhost
      shell: "ssh-keygen -f ~/.ssh/known_hosts -R {{ ansible_host }}"

    - name: Amend local connectivity for first SSH connection to the RaspberryPi
      set_fact:
        ansible_user: "{{ first_bootstrap_user }}"
        bootstrap_user: "{{ bootstrap_user }}"
        ansible_ssh_pass: "{{ first_bootstrap_password }}"
        ansible_become: yes
        ansible_become_user: root

    - include: bootstrap-rpi.yml
